### ISSUE TITLE
Stopped working in IE8

### ISSUE THREAD

**Issue by Twansparant** [dirkgroenen/SVGMagic#29]
Hi there,

The current version 3.0.0 just stopped working for me...
Are you by any chance having problems on your server? The demo doesn't work either anymore in IE8.
I only have the following line in my script:

```javascript
$('img').svgmagic({forceReplacements: true }); // true for debugging
```

Thanks, Toine

**Comment by Twansparant** [comment]
Never mind, working again!
Think it was a short server failure on your end?

**Comment by dirkgroenen** [comment]
Good to hear it's working again. I haven't noticed any downtime on the server so I don't know what could have caused the problem.

Please include the debug log (you can enable it by setting ```debug: true;``` the next time you encounter issues.
