### ISSUE TITLE
Android 2.*

### ISSUE THREAD

**Issue by liinavaker** [dirkgroenen/SVGMagic#30]
![screenshot_2015-02-17_1623](https://cloud.githubusercontent.com/assets/1387279/6229795/07aa51ec-b6c3-11e4-9790-7052be06afb0.png)

**Comment by dirkgroenen** [comment]
As you can read in the text above the image the image is a SVG image which isn't supposed to be converted to a PNG. 
> See it yourself: (assuming you are now using a browser that understands SVG images)

The [demo page](https://dirkgroenen.github.io/SVGMagic/demo.html) contains SVG images which are converted by the plugin.

**Comment by liinavaker** [comment]
Thanks for your quick reply. Sorry I didn't notice the disclaimer above the image. 

But unfortunately I am still not able to get Android 2.3.4 (also 2.3.5 and 2.2.2) show replacement pngs. SVGs are replaced with pngs only when i set forceReplacements to true but I wouldn't want to that because then SVGs in supporting browsers get replaced as well. 

Works great in IE8 (without forceReplacements, svgs get replaced with pngs).

**Comment by dirkgroenen** [comment]
Hmm that's weird. Just tested it on a Galaxy S2 and indeed the images aren't replaced. I'll check it out.

**Comment by dirkgroenen** [comment]
It should be fixed in 3.0.1. Turns out the test I used didn't returned the correct result in Android.
