### ISSUE TITLE
Security warning

### ISSUE THREAD

**Issue by liinavaker** [dirkgroenen/SVGMagic#31]
![fullsizerender 2](https://cloud.githubusercontent.com/assets/1387279/7135484/ec9d438c-e2af-11e4-9eb0-c9665e980c61.jpg)
![fullsizerender](https://cloud.githubusercontent.com/assets/1387279/7135485/ec9ff69a-e2af-11e4-8fe6-b025d7708b36.jpg)

**Comment by dirkgroenen** [comment]
I've renewed the certificate a few weeks ago and according to my pc and several tests the certificate is doing fine. Are you also experiencing this dialog when opening [https://bitlabs.nl](https://bitlabs.nl)?
