### ISSUE TITLE
How can I get it to work locally on my dev machine?

### ISSUE THREAD

**Issue by jessekahner** [dirkgroenen/SVGMagic#9]
I would like to test this out, but I can't, because if I try locally, the connection to svgmagic.bitlabs.nl timesout after a minute.

**Comment by mrdennis** [comment]
A friendly suggestion: I would mention this lack of support for local testing on the SVGMagic home page. Maybe this is obvious for some people but I ended up wasting a lot of time trying to figure out why it wasn't working locally before I came across this thread.

Great plugin. Thanks!

**Comment by dirkgroenen** [comment]
Thanks, just added the extra information in the REAMDE.
